# Generated by Django 5.2.5 on 2025-08-30 14:53

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('key', models.BinaryField()),
                ('iv', models.BinaryField()),
                ('tag', models.BinaryField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(default=files.models.default_expiry)),
            ],
        ),
    ]
