# Generated by Django 6.0.7 on 2026-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='encrypted_data',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='key',
        ),
        migrations.RemoveField(
            model_name='encryptedfile',
            name='tag',
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(default=1, upload_to='encrypted_files/'),
            preserve_default=False,
        ),
    ]
